module.exports = {
  STORE_KEY: 'a56z0fzrNpl^2',
  screen :'',
  time : 0,
  organisationID :'',
  BASE_URL: 'http://139.59.76.223/larder/webservice/',
  home :'home',
  accessToken :'',
  boxId :'',
  ischeck :'0',
  screen :'',
  myAmount :'',
  myCode :'',
  Signin :'Signin',
  Signup :'Signup',
  front_main :'front_main',
  industry :'',
  orderNumber :'',
  categoryID : '',
  token: '',
  member :'',
  accessToken :'3caa375f799b623321148164f3b94e39',
  productname : '',
  username: 'Varun',
  gender: '',
    mobile: '',
  email: '',
  password: '',
  profile:'',
  otps: '',
  userID :'1',
  employeeId :'',
        dob: '',
        blogurl :'',
related:'',
    productid: '',
    cartId :'',
    myid :'',
  derive_category :'derive_category',
  derive_detail_category : 'derive_detail_category',
  info_number :'',
  info_email : '',
  mainid : '',
  user_id:'',
  dervie_detail_of_product : 'dervie_detail_of_product',

  need_help:'need_help',
  COLOR: {
    ORANGE: '#C50',
    DARKBLUE: '#0F3274',
    LIGHTBLUE: '#6EA8DA',
    DARKGRAY: '#999',
  },
};
